# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TasksApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  pod 'FSCalendar'
  pod 'Loaf'

end
